// Deterministic public-API snapshot for every published package.
//
// For each package it enumerates the exported symbols of the public entrypoint
// (src/index.ts) using the TypeScript type checker, then writes a sorted report
// to api-reports/<package>.api.md. `--check` regenerates in memory and fails if
// the committed report is stale, so any change to the public surface that is not
// reviewed and committed breaks CI.

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const ts = require('typescript');

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const reportsDir = path.join(root, 'api-reports');

const PACKAGES = [
  { name: '@processengine/conductor', dir: 'packages/conductor' },
  { name: '@processengine/transport-kafka', dir: 'packages/transport-kafka' },
  { name: '@processengine/storage-postgres', dir: 'packages/storage-postgres' },
];

function loadProgram(packageDir) {
  const configPath = path.join(root, packageDir, 'tsconfig.json');
  const config = ts.readConfigFile(configPath, ts.sys.readFile);
  const parsed = ts.parseJsonConfigFileContent(config.config, ts.sys, path.dirname(configPath));
  const entry = path.join(root, packageDir, 'src/index.ts');
  const program = ts.createProgram({ rootNames: [entry], options: parsed.options });
  return { program, entry };
}

function kindOf(checker, symbol) {
  let resolved = symbol;
  if (resolved.flags & ts.SymbolFlags.Alias) resolved = checker.getAliasedSymbol(resolved);
  const flags = resolved.flags;
  if (flags & ts.SymbolFlags.Class) return 'class';
  if (flags & ts.SymbolFlags.Enum) return 'enum';
  if (flags & ts.SymbolFlags.Function) return 'function';
  if (flags & ts.SymbolFlags.Interface) return 'interface';
  if (flags & ts.SymbolFlags.TypeAlias) return 'type';
  if (flags & ts.SymbolFlags.ValueModule) return 'namespace';
  if (flags & (ts.SymbolFlags.Variable | ts.SymbolFlags.BlockScopedVariable | ts.SymbolFlags.FunctionScopedVariable | ts.SymbolFlags.Property)) return 'const';
  return 'value';
}

function reportFor(pkg) {
  const { program, entry } = loadProgram(pkg.dir);
  const checker = program.getTypeChecker();
  const source = program.getSourceFile(entry);
  if (!source) throw new Error(`Cannot load entrypoint for ${pkg.name}`);
  const moduleSymbol = checker.getSymbolAtLocation(source);
  if (!moduleSymbol) throw new Error(`${pkg.name} entrypoint is not a module`);
  const exports = checker.getExportsOfModule(moduleSymbol)
    .map((symbol) => ({ name: symbol.getName(), kind: kindOf(checker, symbol) }))
    .sort((left, right) => left.name.localeCompare(right.name));
  const lines = [
    `# Public API report — ${pkg.name}`,
    '',
    'Generated by `npm run api:report`. Do not edit by hand. A change here must be',
    'a reviewed, intentional change to the public surface.',
    '',
    ...exports.map((entryItem) => `- ${entryItem.kind} \`${entryItem.name}\``),
    '',
  ];
  return lines.join('\n');
}

const check = process.argv.includes('--check');
await mkdir(reportsDir, { recursive: true });
let drift = false;
for (const pkg of PACKAGES) {
  const content = reportFor(pkg);
  const file = path.join(reportsDir, `${pkg.name.replace(/^@/u, '').replace('/', '-')}.api.md`);
  if (check) {
    const existing = await readFile(file, 'utf8').catch(() => '');
    if (existing !== content) {
      drift = true;
      console.error(`API report drift for ${pkg.name}: ${path.relative(root, file)} is stale. Run \`npm run api:report\`.`);
    } else {
      console.log(`API report up to date: ${pkg.name}`);
    }
  } else {
    await writeFile(file, content);
    console.log(`Wrote ${path.relative(root, file)}`);
  }
}
if (check && drift) process.exit(1);
