// Deterministic public-API snapshot for every published package.
//
// For each package it enumerates the exported symbols of EVERY public entrypoint
// declared in package.json `exports` (root and subpaths such as
// `./testing`, `./worker`, `./migrations`) using the TypeScript type checker,
// then writes a sorted report to api-reports/<package>.api.md with one section per
// entrypoint. `--check` regenerates in memory and fails if a committed report is
// stale, so any change to any public entrypoint that is not reviewed and committed
// breaks CI.

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const ts = require('typescript');

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const reportsDir = path.join(root, 'api-reports');

const PACKAGES = [
  { name: '@processengine/conductor', dir: 'packages/conductor' },
  { name: '@processengine/transport-kafka', dir: 'packages/transport-kafka' },
  { name: '@processengine/storage-postgres', dir: 'packages/storage-postgres' },
];

// Map every `exports` entry that resolves to a built dist/*.js entrypoint back to
// its TypeScript source, so the report tracks the actual published surface.
function entrypoints(packageDir) {
  const manifest = JSON.parse(readFileSync(path.join(root, packageDir, 'package.json'), 'utf8'));
  const result = [];
  for (const [subpath, value] of Object.entries(manifest.exports ?? {})) {
    const target = typeof value === 'string' ? value : value?.import ?? value?.types;
    if (typeof target !== 'string') continue;
    const match = /^\.\/dist\/(.+)\.(?:js|d\.ts)$/u.exec(target);
    if (!match) continue; // e.g. a shipped JSON schema file — not a TS surface
    result.push({ subpath, src: path.join(root, packageDir, 'src', `${match[1]}.ts`) });
  }
  return result.sort((left, right) => left.subpath.localeCompare(right.subpath));
}

function kindOf(checker, symbol) {
  let resolved = symbol;
  if (resolved.flags & ts.SymbolFlags.Alias) resolved = checker.getAliasedSymbol(resolved);
  const flags = resolved.flags;
  if (flags & ts.SymbolFlags.Class) return 'class';
  if (flags & ts.SymbolFlags.Enum) return 'enum';
  if (flags & ts.SymbolFlags.Function) return 'function';
  if (flags & ts.SymbolFlags.Interface) return 'interface';
  if (flags & ts.SymbolFlags.TypeAlias) return 'type';
  if (flags & ts.SymbolFlags.ValueModule) return 'namespace';
  if (flags & (ts.SymbolFlags.Variable | ts.SymbolFlags.BlockScopedVariable | ts.SymbolFlags.FunctionScopedVariable | ts.SymbolFlags.Property)) return 'const';
  return 'value';
}

function exportsOf(packageDir, entries) {
  const configPath = path.join(root, packageDir, 'tsconfig.json');
  const config = ts.readConfigFile(configPath, ts.sys.readFile);
  const parsed = ts.parseJsonConfigFileContent(config.config, ts.sys, path.dirname(configPath));
  const program = ts.createProgram({ rootNames: entries.map((entry) => entry.src), options: parsed.options });
  const checker = program.getTypeChecker();
  return entries.map((entry) => {
    const source = program.getSourceFile(entry.src);
    if (!source) throw new Error(`Cannot load entrypoint ${entry.src}`);
    const moduleSymbol = checker.getSymbolAtLocation(source);
    if (!moduleSymbol) throw new Error(`${entry.src} is not a module`);
    const symbols = checker.getExportsOfModule(moduleSymbol)
      .map((symbol) => ({ name: symbol.getName(), kind: kindOf(checker, symbol) }))
      .sort((left, right) => left.name.localeCompare(right.name));
    return { subpath: entry.subpath, symbols };
  });
}

function reportFor(pkg) {
  const entries = entrypoints(pkg.dir);
  const surfaces = exportsOf(pkg.dir, entries);
  const lines = [
    `# Public API report — ${pkg.name}`,
    '',
    'Generated by `npm run api:report`. Do not edit by hand. A change here must be',
    'a reviewed, intentional change to the public surface. One section per entrypoint',
    'declared in `package.json` exports.',
    '',
  ];
  for (const surface of surfaces) {
    const importPath = surface.subpath === '.' ? pkg.name : `${pkg.name}${surface.subpath.slice(1)}`;
    lines.push(`## \`${importPath}\``, '');
    for (const symbol of surface.symbols) lines.push(`- ${symbol.kind} \`${symbol.name}\``);
    lines.push('');
  }
  return lines.join('\n');
}

const check = process.argv.includes('--check');
await mkdir(reportsDir, { recursive: true });
let drift = false;
for (const pkg of PACKAGES) {
  const content = reportFor(pkg);
  const file = path.join(reportsDir, `${pkg.name.replace(/^@/u, '').replace('/', '-')}.api.md`);
  if (check) {
    const existing = await readFile(file, 'utf8').catch(() => '');
    if (existing !== content) {
      drift = true;
      console.error(`API report drift for ${pkg.name}: ${path.relative(root, file)} is stale. Run \`npm run api:report\`.`);
    } else {
      console.log(`API report up to date: ${pkg.name}`);
    }
  } else {
    await writeFile(file, content);
    console.log(`Wrote ${path.relative(root, file)}`);
  }
}
if (check && drift) process.exit(1);
