export const CORE_OPERATION_ERRORS = Object.freeze({
  DISPATCH_FAILED: 'PROCESSENGINE_DISPATCH_FAILED',
  COMPLETION_TIMEOUT: 'PROCESSENGINE_COMPLETION_TIMEOUT',
});

export const CORE_OPERATION_ERROR_CODES = Object.freeze(Object.values(CORE_OPERATION_ERRORS));
